version: '3'

services:
  telegram-parser:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp_media:/app/temp_media
    restart: always 